# Generated by Django 3.2.4 on 2021-08-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_inform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inform',
        ),
    ]
