# Generated by Django 3.2.4 on 2021-07-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0002_auto_20210702_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название статьи'),
        ),
    ]
