# Generated by Django 3.2.4 on 2021-07-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0005_alter_comments_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='author',
        ),
    ]
