# Generated by Django 3.2.4 on 2021-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0009_alter_comments_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
