# Generated by Django 3.2.4 on 2021-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0010_alter_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.ImageField(height_field=100, null=True, upload_to='article_img', width_field=100),
        ),
    ]
