# Generated by Django 3.2.4 on 2021-08-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0012_alter_articles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(null=True, upload_to='article_img', verbose_name='Изображение статьи'),
        ),
    ]
