# Generated by Django 3.2.4 on 2021-08-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0014_alter_articles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='img',
        ),
    ]
