# Generated by Django 3.2.4 on 2021-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0015_remove_articles_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(null=True, upload_to='article_img', verbose_name='Изображение статьи')),
            ],
        ),
    ]
