# Generated by Django 3.2.4 on 2021-08-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0016_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainblog.articleimage', verbose_name='Изображение статьи'),
        ),
    ]
