# Generated by Django 3.2.4 on 2021-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0020_auto_20210820_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(null=True, upload_to='article_img', verbose_name='Изображение статьи'),
        ),
    ]
