# Generated by Django 3.2.4 on 2021-08-20 21:15

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('mainblog', '0021_alter_articles_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='innerimg',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
