# Generated by Django 3.2.4 on 2021-08-21 13:20

from django.db import migrations, models
import django.db.models.deletion
import mainblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0022_articles_innerimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='innerimg',
        ),
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='article_img', verbose_name='Изображение статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(verbose_name='Основной текст статьи'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mainblog.models.get_image_filename, verbose_name='Image')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainblog.articles')),
            ],
        ),
    ]
