# Generated by Django 3.2.4 on 2021-08-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0023_auto_20210821_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='contentimg',
            field=models.ImageField(blank=True, null=True, upload_to='content_img/%author/%title/', verbose_name='Изображение для контента статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, default='default_article_pixel.jpg', null=True, upload_to='article_img', verbose_name='Изображение заголовка статьи'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
