# Generated by Django 3.2.4 on 2021-08-24 17:08

from django.db import migrations, models
import mainblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0024_auto_20210824_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='contentimg',
            field=models.ImageField(blank=True, null=True, upload_to=mainblog.models.get_upload_path, verbose_name='Изображение для контента статьи'),
        ),
    ]
