# Generated by Django 3.2.4 on 2021-08-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0025_alter_articles_contentimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='contentimg',
        ),
    ]
