# Generated by Django 3.2.4 on 2021-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0026_remove_articles_contentimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsBorsch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование продукта')),
                ('price', models.IntegerField(verbose_name='Стоимость продукта за кг')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
    ]
