# Generated by Django 3.2.7 on 2021-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0028_alter_productsborsch_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsborsch',
            name='grammovka',
            field=models.IntegerField(null=True, verbose_name='Граммовка для литра борща'),
        ),
        migrations.AddField(
            model_name='productsborsch',
            name='kilo',
            field=models.IntegerField(default=1000, null=True, verbose_name='Килограмм'),
        ),
    ]
