# Generated by Django 3.2.9 on 2021-12-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0032_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор комментария'),
        ),
    ]
